---
name: Alien-Charles
version: 0.01
author:
  - 'Daniel Austin <hisso@cpan.org>'
abstract: Simple interaction with Charles Web Debugging Proxy
license: perl
resources:
  license: ~
build_requires:
  Test::More: 0
provides:
  Alien::Charles:
    file: lib/Alien/Charles.pm
    version: 0.01
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
